/**
 * Filelist: common_sve.f
 */
+incdir+${UVMF_HOME}/uvmf_base_pkg
+incdir+${UVMF_HOME}/common/fli_pkg
+incdir+${UVMF_HOME}/common/uvm_co_emulation_utilities/clock
+incdir+${UVMF_HOME}/common/mgc_vip/ahb
+incdir+${UVMF_HOME}/common/utility_packages/qvip_utils_pkg
+incdir+${UVMF_HOME}/common/uvm_co_emulation_utilities/reset
+incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv
${UVMF_HOME}/uvmf_base_pkg/uvmf_base_pkg.sv
${UVMF_HOME}/uvmf_base_pkg/uvmf_base_pkg_hdl.sv
${UVMF_HOME}/common/fli_pkg/fli_pkg.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_master_hdl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_master_hvl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_monitor_hdl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_monitor_hvl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_signal_if.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_slave_hdl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_slave_hvl.sv
${UVMF_HOME}/common/mgc_vip/ace/mgc_ace_v2_signal_if.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_master_hdl.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_master_hvl.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_module_hvl.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_signal_if.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_slave_hdl.sv
${UVMF_HOME}/common/mgc_vip/ahb/mgc_ahb_slave_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_master_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_master_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_monitor_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_monitor_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_signal_if.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_slave_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi/mgc_axi_slave_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_master_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_master_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_monitor_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_monitor_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_signal_if.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_slave_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4/mgc_axi4_slave_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_master_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_master_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_monitor_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_monitor_hvl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_signal_if.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_slave_hdl.sv
${UVMF_HOME}/common/mgc_vip/axi4_v2/mgc_axi4_slave_hvl.sv
${UVMF_HOME}/common/mgc_vip/ethernet/mgc_ethernet_device_hdl.sv
${UVMF_HOME}/common/mgc_vip/ethernet/mgc_ethernet_hvl.sv
${UVMF_HOME}/common/mgc_vip/ethernet/mgc_ethernet_mac_hdl.sv
${UVMF_HOME}/common/mgc_vip/ethernet/mgc_ethernet_signal_if.sv
${UVMF_HOME}/common/modules/AXI_slave_v.v
${UVMF_HOME}/common/modules/ahb_master.v
${UVMF_HOME}/common/modules/ahb_memory_slave_module.sv
${UVMF_HOME}/common/modules/ahb_memory_slave_module_hdl.sv
${UVMF_HOME}/common/modules/ahb_memory_slave_module_hvl.sv
${UVMF_HOME}/common/modules/ahb_slave.v
${UVMF_HOME}/common/modules/apb3_memory_slave_module.sv
${UVMF_HOME}/common/sv_connect/hvl/svdpi.sv
${UVMF_HOME}/common/utility_packages/qvip_utils_pkg/qvip_utils_pkg.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/clock_pkg.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/clock/clock_bfm.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/memload/memload_pkg.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/reset/reset_pkg.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/reset/async_reset_bfm.sv
${UVMF_HOME}/common/uvm_co_emulation_utilities/uvm_co-emulation_utilities/utils/clock/reset/sync_reset_bfm.sv

