## To instantiate this subenv in a higher level, use this structure:
##  qvip_subenvs :
##    - { name: "<instance_name_of_subenv>", type: "qvip_agents" }
uvmf:
  qvip_library:
    version: '2020.1'
    date: '01/23/2020:13:29'
  qvip_environments:
     "qvip_agents":
        agents:
          - name: 'apb_master_0'
            imports:
              - "mvc_pkg"
              - "mgc_apb3_v1_0_pkg"
