# Package make targets
ALU_ENV_PKG =\
+incdir+$(UVMF_HOME)/base_examples/verification_ip/environment_packages/alu_env_pkg \
$(UVMF_HOME)/base_examples/verification_ip/environment_packages/alu_env_pkg/alu_env_pkg.sv

comp_alu_env_pkg:
	$(HVL_COMP_CMD) $(ALU_ENV_PKG)

