# Package make targets
AHB2WB_ENV_PKG =\
+incdir+$(UVMF_HOME)/base_examples/verification_ip/environment_packages/ahb2wb_env_pkg \
$(UVMF_HOME)/base_examples/verification_ip/environment_packages/ahb2wb_env_pkg/ahb2wb_env_pkg.sv

comp_ahb2wb_env_pkg:
	$(HVL_COMP_CMD) $(AHB2WB_ENV_PKG)

