uvmf:
  environments:
    alu:
      agents:
      - initiator_responder: INITIATOR
        name: alu_in_agent
        parameters:
        - name: ALU_IN_OP_WIDTH
          value: ALU_IN_OP_WIDTH
        type: alu_in
      - initiator_responder: INITIATOR
        name: alu_out_agent
        parameters:
        - name: ALU_OUT_RESULT_WIDTH
          value: ALU_OUT_RESULT_WIDTH
        type: alu_out
      analysis_components:
      - name: alu_pred
        parameters: []
        type: alu_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: mvc_pkg
      - name: mgc_apb3_v1_0_pkg
      non_uvmf_components: []
      parameters:
      - name: ALU_IN_OP_WIDTH
        type: int
        value: '8'
      - name: ALU_OUT_RESULT_WIDTH
        type: int
        value: '16'
      - name: APB_ADDR_WIDTH
        type: int
        value: '32'
      - name: APB_WDATA_WIDTH
        type: int
        value: '32'
      - name: APB_RDATA_WIDTH
        type: int
        value: '32'
      qvip_memory_agents: []
      qvip_subenvs:
      - name: qvip_agents_env
        type: qvip_agents
      register_model:
        maps:
        - interface: alu_in_agent
          name: apb_map
        use_adapter: 'True'
        use_explicit_prediction: 'True'
      scoreboards:
      - name: alu_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: 'alu_out_transaction #(.ALU_OUT_RESULT_WIDTH(ALU_OUT_RESULT_WIDTH))'
      subenvs: []
      tlm_connections:
      - driver: alu_in_agent.monitored_ap
        receiver: alu_pred.alu_in_agent_ae
      - driver: alu_pred.alu_sb_ap
        receiver: alu_sb.expected_analysis_export
      - driver: alu_out_agent.monitored_ap
        receiver: alu_sb.actual_analysis_export
