
$UVMF_HOME/base_examples/verification_ip/interface_packages/alu_in_pkg/alu_in_pkg_hdl.sv

$UVMF_HOME/base_examples/verification_ip/interface_packages/alu_in_pkg/src/alu_in_if.sv
$UVMF_HOME/base_examples/verification_ip/interface_packages/alu_in_pkg/src/alu_in_monitor_bfm.sv
$UVMF_HOME/base_examples/verification_ip/interface_packages/alu_in_pkg/src/alu_in_driver_bfm.sv
