# Package make targets
VIP_AXI4_ENV_PKG =\
+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/vip_axi4_env_pkg \
${UVMF_VIP_LIBRARY_HOME}/environment_packages/vip_axi4_env_pkg/vip_axi4_env_pkg.sv

comp_vip_axi4_env_pkg:
	${HVL_COMP_CMD} $(VIP_AXI4_ENV_PKG)

