./api_files/mem_if_config.py --yaml
./api_files/pkt_if_config.py --yaml
./api_files/dma_if_config.py --yaml
./api_files/block_a_env_config.py --yaml
./api_files/block_a_bench_config.py --yaml
./api_files/block_b_env_config.py --yaml
./api_files/block_b_bench_config.py --yaml
./api_files/chip_env_config.py --yaml
./api_files/chip_bench_config.py --yaml
