+incdir+../../src/globals/
+incdir+../../src/hvl_top/test/sequences/master_sequences/
+incdir+../../src/hvl_top/master/
+incdir+../../src/hdl_top/master_agent_bfm/ 
+incdir+../../src/hvl_top/env/virtual_sequencer/
+incdir+../../src/hvl_top/test/virtual_sequences/
+incdir+../../src/hvl_top/env
+incdir+../../src/hvl_top/slave
+incdir+../../src/hvl_top/test/sequences/slave_sequences/
+incdir+../../src/hvl_top/test
+incdir+../../src/hdl_top/slave_agent_bfm
+incdir+../../src/hdl_top/i3c_interface
../../src/globals/i3c_global_pkg.sv
../../src/hvl_top/master/i3c_master_pkg.sv
../../src/hvl_top/slave/i3c_slave_pkg.sv
../../src/hvl_top/test/sequences/master_sequences/i3c_master_seq_pkg.sv
../../src/hvl_top/test/sequences/slave_sequences/i3c_slave_seq_pkg.sv
../../src/hvl_top/env/i3c_env_pkg.sv
../../src/hvl_top/test/virtual_sequences/i3c_virtual_seq_pkg.sv
../../src/hvl_top/test/i3c_test_pkg.sv
../../src/hdl_top/i3c_interface/i3c_if.sv
../../src/hdl_top/master_agent_bfm/i3c_master_driver_bfm.sv
../../src/hdl_top/master_agent_bfm/i3c_master_monitor_bfm.sv
../../src/hdl_top/master_agent_bfm/i3c_master_agent_bfm.sv
../../src/hdl_top/slave_agent_bfm/i3c_slave_driver_bfm.sv
../../src/hdl_top/slave_agent_bfm/i3c_slave_monitor_bfm.sv
../../src/hdl_top/slave_agent_bfm/i3c_slave_agent_bfm.sv
../../src/hdl_top/hdl_top.sv
../../src/hvl_top/hvl_top.sv 
