#!/bin/bash

LD_LIBRARY_PATH=${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-6.2.0_vcs:${VCS_HOME}/gnu/linux/gcc-6.2.0/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

vcs -sverilog -ntb_opts uvm -debug_access+w -quiet  -full64 -timescale=1ps/1ps \
    -ld ${VCS_HOME}/gnu/linux/gcc-6.2.0/xbin/g++ \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv \
    ${QUESTA_MVC_HOME}/include/questa_mvc_svapi.sv \
    +define+MAP_PROT_ATTR ${QUESTA_MVC_HOME}/questa_mvc_src/sv/mvc_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4 ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/mgc_axi4_v1_0_pkg.sv \
    +incdir+../config_policies \
    ../config_policies/scatter_gather_dma_qvip_params_pkg.sv \
    scatter_gather_dma_qvip_pkg.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_master.sv \
    +incdir+${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules ${QUESTA_MVC_HOME}/questa_mvc_src/sv/axi4/modules/axi4_slave.sv \
    default_clk_gen.sv \
    default_reset_gen.sv \
    hdl_scatter_gather_dma_qvip.sv \
    hvl_scatter_gather_dma_qvip.sv \
    -syslib ${QUESTA_MVC_HOME}/questa_mvc_core/linux_x86_64_gcc-6.2.0_vcs/libaxi4_IN_SystemVerilog_VCS_full.so

./simv +UVM_TESTNAME=scatter_gather_dma_qvip_test_base +SEQ=scatter_gather_dma_qvip_vseq_base
