module i3c_daa_fsm (
  input   wire          clk,
  input   wire          rst_n,
  
  input   wire          start_daa,  // issued from CMD FSM
  output  reg           daa_done,   // notifies end of DAA
  output  reg           start_r,    // start-repeat issued to bit engine
  output  reg           push_pull,  // open-drain, push-pull functionality

  // bit engine interface
  output  reg           valid,      // start / issue commands to bit engine
  output  reg           rd_wr,      // 1: read; 0: write
  output  reg   [7:0]   tx_data,    // byte issued to bit engine
  output  reg           arb_mode,   // pause bit engine for arbritration
  input   wire          sda_i,      // sampled SDA bus
  input   wire          scl_i,      // sampled SCL bus
  input   wire          busy,       // issued by bit engine
  input   wire          nack,       // issued by bit engine
  input   wire          be_done,    // bit engine transaction done

  // for device table
  output  reg   [47:0]  pid,
  output  reg   [7:0]   bcr,
  output  reg   [7:0]   dcr,
  output  reg   [6:0]   dyn_addr,
  output  reg           dt_en       // device table write-enable
);

// FSM encoding
localparam [4:0]
  IDLE        = 5'd0, // wait for start_daa
  SEND_7E_W   = 5'd1, // broadcast 7E + W
  SEND_ENTDAA = 5'd2, // broadcast 07
  REP_START   = 5'd3, // request start-repeat to bit engine
  SEND_7E_R   = 5'd4, // broadcast 7E + R
  ARB_BITS    = 5'd5, // get {PID, BCR, DCR}
  ASSIGN      = 5'd6, // assign dynamic address
  LOOP        = 5'd7, // go to REP_START
  STOP        = 5'd8; // end DAA

reg   [4:0]   state, next;          // FSM registers
reg   [6:0]   bit_cnt;              // for arb_shift
reg   [63:0]  arb_shift;            // {PID, BCR, DCR}

wire          parity = ~^dyn_addr;  // for dynamic address

// SCL edge detection logic
reg   scl_q, scl_qq;
wire  scl_rise = (scl_q == 1'b1) && (scl_qq == 1'b0);
wire  scl_fall = (scl_q == 1'b0) && (scl_qq == 1'b1);
always @(posedge clk or negedge rst_n) begin
  if (!rst_n) begin
    scl_q  <= 1'b1;
    scl_qq <= 1'b1;
  end else begin
    scl_q  <= scl_i;
    scl_qq <= scl_q;
  end
end

// FSM: reset logic
always @(posedge clk or negedge rst_n) begin
  if (!rst_n) state <= IDLE;
  else      state <= next;
end

// FSM: next-state logic
always @* begin
  case (state)
    IDLE        : next = start_daa          ? SEND_7E_W : IDLE;
    SEND_7E_W   : next = be_done && !busy   ? nack      ? STOP : SEND_ENTDAA : SEND_7E_W;
    SEND_ENTDAA : next = be_done && !busy   ? nack      ? STOP : REP_START   : SEND_ENTDAA;
    REP_START   : next = !busy && start_r   ? SEND_7E_R : REP_START;
    SEND_7E_R   : next = be_done            ? nack      ? STOP : ARB_BITS    : SEND_7E_R;
    ARB_BITS    : next = (bit_cnt == 7'd0)  ? ASSIGN    : ARB_BITS;
    ASSIGN      : next = be_done && !busy   ? LOOP      : ASSIGN;
    LOOP        : next = nack               ? STOP      : REP_START;
    STOP        : next = IDLE;
    default     : next = IDLE;
  endcase
end

// FSM: output / data logic
always @(posedge clk or negedge rst_n) begin
  if (!rst_n) begin
    valid     <= 'b0;
    rd_wr     <= 'b0;
    tx_data   <= 'b0;
    arb_mode  <= 'b0;
    bit_cnt   <= 7'd64;
    arb_shift <= 'b0;
    pid       <= 'b0;
    bcr       <= 'b0;
    dcr       <= 'b0;
    dyn_addr  <= 7'h08;
    daa_done  <= 'b0;
    start_r   <= 'b0;
    push_pull <= 'b0;
    dt_en     <= 'b0;
  end else begin
    // defaults
    valid    <= 1'b0;
    start_r  <= 1'b0;
    daa_done <= 1'b0;
    dt_en    <= 1'b0; 
    case (state)
      SEND_7E_W: begin
        push_pull <= 1'b0;
        valid     <= !busy && !be_done ? 1'b1 : 1'b0;
        rd_wr     <= 1'b0;
        tx_data   <= {7'h7E, 1'b0}; // 7'h7E + W
      end
      SEND_ENTDAA: begin
        push_pull <= 1'b1;
        valid     <= !busy && !be_done ? 1'b1 : 1'b0;
        rd_wr     <= 1'b0;
        tx_data   <= 8'h07;         // ENTDAA
      end
      REP_START: begin
        start_r <= 1'b1;          // START generated by bit engine
      end
      SEND_7E_R: begin
        push_pull <= 1'b1;
        valid     <= !busy && !be_done ? 1'b1 : 1'b0;
        rd_wr     <= 1'b0;
        tx_data   <= {7'h7E, 1'b1}; // 7'h7E + R
        arb_mode  <= 1'b0;
      end
      ARB_BITS: begin
        push_pull <= 1'b1;
        arb_mode  <= 1'b1;         // RELEASE SDA
        if (scl_rise) begin
          arb_shift <= {arb_shift[62:0], sda_i};
          bit_cnt   <= bit_cnt - 1;
        end
      end
      ASSIGN: begin
        arb_mode <= 1'b0;
        pid      <= arb_shift[63:16];
        bcr      <= arb_shift[15:8];
        dcr      <= arb_shift[7:0];
        valid    <= !busy ? 1 : 0;
        rd_wr    <= 1'b0;
        tx_data  <= {dyn_addr, parity};
        bit_cnt  <= 7'd64;
      end
      LOOP: begin
        dt_en    <= 1'b1; 
        dyn_addr <= dyn_addr + 1;
      end
      STOP: begin
        valid    <= 1'b0;
        daa_done <= 1'b1;
      end
    endcase
  end
end

endmodule