# Package make targets
GPIO_EXAMPLE_ENV_PKG =\
+incdir+$(UVMF_HOME)/base_examples/verification_ip/environment_packages/gpio_example_env_pkg \
$(UVMF_HOME)/base_examples/verification_ip/environment_packages/gpio_example_env_pkg/gpio_example_env_pkg.sv

comp_gpio_example_env_pkg:
	$(HVL_COMP_CMD) $(GPIO_EXAMPLE_ENV_PKG)

