cd ..
./scripts/run.csh ./base_examples/project_benches/ahb2spi/sim
./scripts/run.csh ./base_examples/project_benches/ahb2wb/sim
./scripts/run.csh ./base_examples/project_benches/alu/sim
./scripts/run.csh ./base_examples/project_benches/gpio_example/sim
./scripts/run.csh ./base_examples/project_benches/wb2spi/sim
./scripts/run.csh ./jpeg_example/project_benches/jpeg_bench/sim
./scripts/run.csh ./other_examples/project_benches/ahb2spi_2kds/sim
./scripts/run.csh ./other_examples/project_benches/ahb2wb_2kds/sim
./scripts/run.csh ./other_examples/project_benches/sha3/sim
./scripts/run.csh ./other_examples/project_benches/wb2spi_2kds/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_ahb_example/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_axi3_ahb_bench/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_axi3_example/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_axi4_example/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_ethernet_parallel/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_ethernet_serial/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_pcie_3.0_pipe_example/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_pcie_3.0_serial_example/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_usb3_pipe_example_bench/sim
./scripts/run.csh ./vista_examples/project_benches/alu/sim
./scripts/run.csh ./vip_examples/project_benches/vip_ahb_example/sim
./scripts/run.csh ./vip_examples/project_benches/vip_axi3_ahb_bench/sim
./scripts/run.csh ./vip_examples/project_benches/vip_axi3_example/sim
./scripts/run.csh ./vip_examples/project_benches/vip_axi4_example/sim
