uvmf:
  environments:
    alu:
      agents:
      - initiator_responder: INITIATOR
        name: alu_in_agent
        type: alu_in
      - initiator_responder: INITIATOR
        name: alu_out_agent
        type: alu_out
      analysis_components:
      - name: alu_pred
        parameters: []
        type: alu_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: alu_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: alu_out_transaction
      subenvs: []
      tlm_connections:
      - driver: alu_in_agent.monitored_ap
        receiver: alu_pred.alu_in_agent_ae
      - driver: alu_pred.alu_sb_ap
        receiver: alu_sb.expected_analysis_export
      - driver: alu_out_agent.monitored_ap
        receiver: alu_sb.actual_analysis_export
