#THIS FILE ALLOWS YOU TO ADD OR MODIFY THE STANDARD PP VARIABLES
#THIS FILE IS CALLED BY THE TOOL WRAPPER SCRIPTS AFTER THE DEFAULT VARIABLES ARE SET
#ALLTHOUGH IT IT IS POSSIBLE TO OVERRIDE TOOL PATHS HERE IT WOULD BE BETTER TO CHANGE THE TOOLPATH.SH FILE OR BETTER STILL USE TEH PROJECT SETUP TOOL
#THESE VARIABLES WILL APPLY TO EVERYONE IN THE PROJECT IF YOU COMMIT THIS FILE 
#EXAMPLE: IF YOU WANT TO ADD A VARIBLE CALLED "EXTERNAL_SHARED_IP"
# ADD THE FOLLOWING LINE (WITHOUT THE COMMENT CHAR). NOTE NO SPACE AFTER THE = 

#EXPORT EXTERNAL_SHARED_IP=/PROJECTS/MY_PROJECT/SHARED_IP
