# Package make targets
WB2SPI_ENV_PKG =\
+incdir+$(UVMF_HOME)/base_examples/verification_ip/environment_packages/wb2spi_env_pkg \
$(UVMF_HOME)/base_examples/verification_ip/environment_packages/wb2spi_env_pkg/registers/wb2spi_reg_pkg.sv \
$(UVMF_HOME)/base_examples/verification_ip/environment_packages/wb2spi_env_pkg/wb2spi_env_pkg.sv

comp_wb2spi_env_pkg:
	$(HVL_COMP_CMD) $(WB2SPI_ENV_PKG)


