QVIP_UTILS_PKG         = \
+incdir+$(VIP_HOME)/questa_mvc_src/sv \
+incdir+$(UVMF_HOME)/common/utility_packages/qvip_utils_pkg \
$(UVMF_HOME)/common/utility_packages/qvip_utils_pkg/qvip_utils_pkg.sv

comp_qvip_utils_pkg:
	$(HVL_COMP_CMD) $(QVIP_UTILS_PKG)

