cd ..
./scripts/run.csh ./base_examples/project_benches/ahb2spi/sim
./scripts/run.csh ./base_examples/project_benches/ahb2wb/sim
./scripts/run.csh ./base_examples/project_benches/alu/sim
./scripts/run.csh ./base_examples/project_benches/gpio_example/sim
./scripts/run.csh ./base_examples/project_benches/wb2spi/sim
./scripts/run.csh ./vip_examples/project_benches/qvip_axi4_example/sim
./scripts/run.csh ./vip_examples/project_benches/vip_axi4_example/sim
./scripts/run.csh ./vista_examples/project_benches/alu/sim
