$UVMF_VIP_LIBRARY_HOME/interface_packages/spi_pkg/spi_pkg_hdl.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/spi_pkg/src/spi_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/spi_pkg/src/spi_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/spi_pkg/src/spi_driver_bfm.sv
